# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=999999)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='images',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliexpress.Images'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliexpress.Price'),
        ),
        migrations.AddField(
            model_name='goods',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliexpress.Rate'),
        ),
    ]
