# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='date_time',
            new_name='created_at',
        ),
    ]
