# Generated by Django 2.0.1 on 2018-01-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliexpress', '0002_auto_20180102_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9999999),
        ),
    ]
